spring:
  application:
    name: zelin_codez
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/zelin_codez?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    # 数据库用户名
    username: root
    # 数据库密码
    password: 111111
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.qysoft.zelin_codez.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-flex:
  mapper-locations: classpath:/mapper/*.xml
